### PR TITLE
Add audience count field to sponsoring form

### LINKED ISSUE #4: Add audience count field to sponsoring form
TODO!

### PR DESCRIPTION
**Pull request by codeheroics**
Fix #4 
Tested to be sure that data is correctly added to the desc field (but I did not actually try to post anything to Trello with a real config.json configured)

Depending on which one is merged first, this or #5 will have to be amended.

(Also added missing mocha devDep to run the modified tests)

### CODE REVIEW

**Comment by risseraka** [comment]
Nice job!
Merged #5, could you rebase and test please? Thanks!

**Comment by codeheroics** [comment]
PR updated.

Did you want an automatic test of the different possible description labels, or just for me to test if it still worked after rebasing?

**Comment by risseraka** [comment]
Just wanted you to launch tests post-rebase.
We're good to go! Merging.

**Comment by risseraka** [comment]
@francois2metz hey François, any news on this?
I don't see it deployed at http://parisjstalks.nodejitsu.com/sponsoring.

**Pull request merged**
