### PR TITLE
Adding a "public target" input for talk proposal

### PR DESCRIPTION
**Pull request by molokoloco**

### CODE REVIEW

**Comment by francois2metz** [comment]
You need to modify the server side too you know?

**Comment by molokoloco** [comment]
Fuck like hell !

A do a form with jQUery plugins, don't know

that not automated ?

On Mon, Oct 14, 2013 at 10:19 PM, François de Metz <notifications@github.com

> wrote:
> 
> You need to modify the server side too you know?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/parisjs/parisjs-talks-submit/pull/1#issuecomment-26285387
> .

## 

*Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
http://b2bweb.fr

**Comment by molokoloco** [comment]
Ca roule toi ?

Ca va ?

Ce serait cool de se recroisser quand même ^^

On Mon, Oct 14, 2013 at 10:21 PM, Julien G molokoloco@gmail.com wrote:

> Fuck like hell !
> 
> A do a form with jQUery plugins, don't know
> 
> that not automated ?
> 
> On Mon, Oct 14, 2013 at 10:19 PM, François de Metz <
> notifications@github.com> wrote:
> 
> > You need to modify the server side too you know?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/parisjs/parisjs-talks-submit/pull/1#issuecomment-26285387
> > .
> 
> ## 
> 
> *Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
> 13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
> molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
> http://b2bweb.fr

## 

*Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
http://b2bweb.fr

**Comment by molokoloco** [comment]
Cette semaine je ne peux pas mais.. .t'es dans le coin semaine prochaine ?

On Mon, Oct 14, 2013 at 10:21 PM, Julien G molokoloco@gmail.com wrote:

> Ca roule toi ?
> 
> Ca va ?
> 
> Ce serait cool de se recroisser quand même ^^
> 
> On Mon, Oct 14, 2013 at 10:21 PM, Julien G molokoloco@gmail.com wrote:
> 
> > Fuck like hell !
> > 
> > A do a form with jQUery plugins, don't know
> > 
> > that not automated ?
> > 
> > On Mon, Oct 14, 2013 at 10:19 PM, François de Metz <
> > notifications@github.com> wrote:
> > 
> > > You need to modify the server side too you know?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHubhttps://github.com/parisjs/parisjs-talks-submit/pull/1#issuecomment-26285387
> > > .
> > 
> > ## 
> > 
> > *Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
> > 13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
> > molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
> > http://b2bweb.fr
> 
> ## 
> 
> *Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
> 13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
> molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
> http://b2bweb.fr

## 

*Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
http://b2bweb.fr

**Comment by molokoloco** [comment]
ou pastôt vendredi soir

On Mon, Oct 14, 2013 at 10:22 PM, Julien G molokoloco@gmail.com wrote:

> Cette semaine je ne peux pas mais.. .t'es dans le coin semaine prochaine ?
> 
> On Mon, Oct 14, 2013 at 10:21 PM, Julien G molokoloco@gmail.com wrote:
> 
> > Ca roule toi ?
> > 
> > Ca va ?
> > 
> > Ce serait cool de se recroisser quand même ^^
> > 
> > On Mon, Oct 14, 2013 at 10:21 PM, Julien G molokoloco@gmail.com wrote:
> > 
> > > Fuck like hell !
> > > 
> > > A do a form with jQUery plugins, don't know
> > > 
> > > that not automated ?
> > > 
> > > On Mon, Oct 14, 2013 at 10:19 PM, François de Metz <
> > > notifications@github.com> wrote:
> > > 
> > > > You need to modify the server side too you know?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHubhttps://github.com/parisjs/parisjs-talks-submit/pull/1#issuecomment-26285387
> > > > .
> > > 
> > > ## 
> > > 
> > > *Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
> > > 13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
> > > molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
> > > http://b2bweb.fr
> > 
> > ## 
> > 
> > *Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
> > 13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
> > molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
> > http://b2bweb.fr
> 
> ## 
> 
> *Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
> 13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
> molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
> http://b2bweb.fr

## 

*Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
http://b2bweb.fr

**Comment by molokoloco** [comment]
​IRC ? gTalk ? NoWay ? Fuck ? FuckNot ? #Yeah​

**Comment by molokoloco** [comment]
DO YOU WANT MY UGLY PHP TO DO THE WORK ?

On Mon, Oct 14, 2013 at 10:27 PM, Julien G molokoloco@gmail.com wrote:

> ​IRC ? gTalk ? NoWay ? Fuck ? FuckNot ? #Yeah​

## 

*Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
http://b2bweb.fr

**Comment by molokoloco** [comment]
T'es pas là ?​

​Ou je dois le prendre mal ?​

**Comment by MathRobin** [comment]
:+1:

**Comment by molokoloco** [comment]
oups - only to say that what intended to be a private fucking  message -
Sorry guys...

On Mon, Oct 14, 2013 at 11:32 PM, Mathieu ROBIN notifications@github.comwrote:

> [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/parisjs/parisjs-talks-submit/pull/1#issuecomment-26290653
> .

## 

*Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
http://b2bweb.fr

**Comment by tbassetto** [comment]
Now it will be public forever.

deal_with_it91

**Comment by molokoloco** [comment]
Je ne trouve pas le "server-side" qui reçoit le formulaire..
en tout cas, je ne pense pas que ce soit ici ?
https://github.com/parisjs/parisjs-talks-submit/blob/master/server.js
https://github.com/parisjs/parisjs-talks-submit/blob/master/lib/app.js

Hier soir dans mon empressement j'ai aussi été un peu vite..
J'ai corrigé ici :
https://github.com/parisjs/parisjs-talks-submit/pull/2 (franglais
- id du champs select)
  -      label(for="public") Niveau de la présentation
-      span.help-block Si votre talk cible un public particulier ?
-      select#type(name="public")
-        option(value="public") Tout public
-        option(value="noob") Débutant (I will help you start)
-        option(value="advanced") Avancé (How to do it well)

Je suis pas admin sur le repos donc je ne peux rien faire de plus

Amicalement

Julien G

On Tue, Oct 15, 2013 at 12:50 PM, Thomas Bassetto
notifications@github.comwrote:

> Now it will be public forever.
> 
> [image: deal_with_it91]https://f.cloud.github.com/assets/211630/1332919/916ed2e0-3587-11e3-8097-e9b0f7fc2223.jpg
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/parisjs/parisjs-talks-submit/pull/1#issuecomment-26324726
> .

## 

*Julien Guézennec *+336 61 75 64 98 ​​​( ͡° ͜ʖ ͡°)
13, Avenue Léon Gourdault, Bat F. Esc. 2, 94600 Choisy
molokoloco@gmail.com - @molokoloco https://twitter.com/molokoloco/ -
http://b2bweb.fr

**Comment by francois2metz** [comment]
Ahaha. Still epic after all these years. :kiss:

**Comment by molokoloco** [comment]
All "that"  year ✌

**Pull request closed without merging**
