### PR TITLE
[RFR] Adding sponsoring form to /sponsoring

### PR DESCRIPTION
**Pull request by risseraka**
@francois2metz please review!

NB: a "Sponsoring" list needs to be created in trello and its ID to be added in config.json under "idSponsoring" key.

### CODE REVIEW

**Comment by risseraka** [comment]
Oops, forgot to add tests, WIP.

**Comment by risseraka** [comment]
OK, tests have been added and are all green!

Ready for review.

**Comment by francois2metz** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:  I <3 code with tests.

**Comment by francois2metz** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:  Thanks for your contribution :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by risseraka** [comment]
Here's what's still to do:
- a "Sponsoring" list to be created in trello;
- its ID to be added in config.json under "idSponsoring" key;
- add the form to parisjs.org website.

Thanks for the merge. : )

**Comment by francois2metz** [comment]
I'm working on a few tweaks and I will deploy it.

**Comment by risseraka** [comment]
Great!

Cheers.

**Comment by francois2metz** [comment]
Deployed.
- https://trello.com/b/wyiHbTlT/sponsoring
- http://parisjstalks.nodejitsu.com/sponsoring

:kiss:

**Comment by risseraka** [comment]
https://trello.com/b/wyiHbTlT/sponsoring

Board not found, is it private?

On Sun, Apr 19, 2015 at 8:32 PM, François de Metz notifications@github.com
wrote:

> Deployed.
> - https://trello.com/b/wyiHbTlT/sponsoring
> - http://parisjstalks.nodejitsu.com/sponsoring
> 
> [image: :kiss:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/parisjs/parisjs-talks-submit/pull/3#issuecomment-94303869
> .

## 

Adrien Risser,
Freelance Node.js Consultant
M. +33 6 59 60 32 58

**Comment by francois2metz** [comment]
My bad. Fixed

**Comment by risseraka** [comment]
Cool!

Last thing to update is About section at http://parisjs.org/.

On Sun, Apr 19, 2015 at 8:37 PM, François de Metz notifications@github.com
wrote:

> My bad. Fixed
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/parisjs/parisjs-talks-submit/pull/3#issuecomment-94304102
> .

## 

Adrien Risser,
Freelance Node.js Consultant
M. +33 6 59 60 32 58

**Pull request merged**
